[package]
name = "victus-backend"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
victus-common = { path = "../common" }
zbus.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
serde.workspace = true
parking_lot = "0.12"

